version: '3.8'

services:
  locust:
    build:
      context: .
    ports:
      - "8089:8089"
    volumes:
      - .:/mnt/locust
    working_dir: /mnt/locust
    command: >
      locust -f locustfile.py --host=http://host.docker.internal:8080