services:
  postgres:
    image: postgres:16
    container_name: event_postgres
    ports:
      - "5432:5432"
    shm_size: 1g
    environment:
      POSTGRES_DB: event_db
      POSTGRES_USER: event_user
      POSTGRES_PASSWORD: event_pass
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always

  redis:
    image: redis:7.4
    container_name: event_redis
    ports:
      - "6379:6379"
    restart: always

  event-tracker:
    image: event-tracker:latest
    container_name: event_tracker
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  user-service:
    image: user-service:latest
    container_name: user_service
    depends_on:
      - event-tracker
      - postgres
      - redis
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EVENT_TRACKER_URL=http://event-tracker:8080

  event-locust:
    container_name: event_locust
    build:
      context: ./event-tracker/locust
    ports:
      - "8089:8089"
    volumes:
      - ./event-tracker/locust:/mnt/locust
    working_dir: /mnt/locust
    command: >
      locust -f locustfile.py --host=http://host.docker.internal:8080

  user-locust:
    container_name: user_locust
    build:
      context: ./user-service/locust
    ports:
      - "8090:8090"
    volumes:
      - ./user-service/locust:/mnt/locust
    working_dir: /mnt/locust
    command: >
      locust -f locustfile.py --host=http://host.docker.internal:8081 --web-port 8090

networks:
  default:
    driver: bridge