version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: event_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: event_db
      POSTGRES_USER: event_user
      POSTGRES_PASSWORD: event_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7.4
    container_name: event_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: always

  locust:
    container_name: event_locust
    build:
      context: ./locust
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/mnt/locust
    working_dir: /mnt/locust
    command: >
      locust -f locustfile.py --host=http://host.docker.internal:8080

volumes:
  pgdata:
  redisdata: