spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  application:
    name: event-tracker

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/event_db
    username: event_user
    password: event_pass

  codec:
    max-in-memory-size: 10MB

  main:
    web-application-type: reactive

  data:
    redis:
      host: localhost
      port: 6379


logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
    org.springframework.data.redis: DEBUG

---

spring:
  config:
    activate:
      on-profile: test

  data:
    redis:
      host: localhost
      port: 63790